# Generated by Django 5.2.17 on 2026-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
    ]
